CREATE SCHEMA authentication_server_db;

SET SEARCH_PATH TO authentication_server_db;

DROP TABLE IF EXISTS T_USER_TEST;

CREATE TABLE T_USER_TEST (
  ID SERIAL NOT NULL,
  USER_NAME VARCHAR(64) NOT NULL,
  AGE TINYINT NOT NULL,
  PRIMARY KEY (ID)
);
